title: Asylum Redux Dispatch
description: Semi in-character field newsletters for the Asylum Redux Arma 3 server.
url: https://www.devotary.xyz
markdown: kramdown
permalink: /news/:year-:month-:day-:slug/

